In [2]:
import numpy as np

In [3]:
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [7]:
a1.size

3

In [8]:
a1.shape

(3,)

In [9]:
a1.ndim

1

In [13]:
a2=np.array([[2,3,4],[4,5,60]])

In [14]:
a2

array([[ 2,  3,  4],
       [ 4,  5, 60]])

In [15]:
a2.size

6

In [16]:
a2.ndim

2

In [17]:
import pandas as pd

In [18]:
df=pd.DataFrame(a2)

In [19]:
df

0  1   2
0  2  3   4
1  4  5  60

In [23]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 6, 7, 2, 7],
         [3, 6, 0, 3, 3],
         [6, 8, 4, 4, 8],
         [6, 0, 1, 5, 3]],

        [[2, 4, 5, 9, 9],
         [1, 1, 4, 7, 1],
         [3, 4, 4, 4, 7],
         [4, 2, 2, 1, 7]],

        [[1, 1, 4, 1, 2],
         [0, 9, 6, 0, 0],
         [3, 0, 7, 6, 9],
         [0, 3, 5, 5, 9]]],


       [[[2, 4, 7, 5, 1],
         [8, 7, 9, 1, 9],
         [3, 2, 6, 3, 7],
         [8, 2, 7, 1, 6]],

        [[5, 3, 4, 3, 8],
         [3, 9, 1, 9, 4],
         [6, 9, 0, 2, 1],
         [6, 1, 3, 1, 5]],

        [[4, 4, 4, 6, 2],
         [4, 0, 6, 4, 5],
         [6, 2, 6, 2, 7],
         [0, 7, 7, 6, 1]]]], dtype=int32)

In [24]:
a4.ndim

4

In [25]:
a4.size

120

In [27]:
a4.shape

(2, 3, 4, 5)

In [28]:
a4[:,:,:,:2]

array([[[[3, 6],
         [3, 6],
         [6, 8],
         [6, 0]],

        [[2, 4],
         [1, 1],
         [3, 4],
         [4, 2]],

        [[1, 1],
         [0, 9],
         [3, 0],
         [0, 3]]],


       [[[2, 4],
         [8, 7],
         [3, 2],
         [8, 2]],

        [[5, 3],
         [3, 9],
         [6, 9],
         [6, 1]],

        [[4, 4],
         [4, 0],
         [6, 2],
         [0, 7]]]], dtype=int32)

In [29]:
a1

array([1, 2, 3])

# Manipulation of Arrays

## Arithmetic

In [31]:
ones= np.ones(3)

In [32]:
ones

array([1., 1., 1.])

In [33]:
a1+ones

array([2., 3., 4.])

# Aggregation


%timeit is magic funtion

In [36]:
a5=np.random.random(10000)
a5.size

10000

In [37]:
%timeit sum(a5)
%timeit np.sum(a5)

977 μs ± 31 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
8.52 μs ± 90 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
